language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
env:
  global:
    secure: u1kjl2PMWkDPmOpecNjZ4VJu4ctadcgpV8mgfU3m8yVzQ0HGlkQyN8VbMDd703tnVrvKqYRPLXHWdde64knaxCi5BGK/g3yPw8xBrNyXW7vJ1QfbhJeQNXlnfNfThmcZPL9kt+3UNlqJylzKuALitS/k4Yq+BJK27oswfG2jpWd0P+LpsGpz5o2p1QMJlMMJ/JsYceRAw07KJmK8iwHEtGh9WfDA/XiYrE9laknCYg4+G52XAjuPPtJqaFTqXHr0wUMGCOEoYlFH1m2EOU/dxmAdguctVh3CsHWmAlPJQCaQjB+hN053YWGvcymbJgaqBTxXiRiMsgKwV3rvqmQpKUxMEpELI4F8YCWVneU2gZxYdYB5V1pqgRgOuHHD+Oin3jCcrtzVl5ev54CHvaDFYxk6AwsdZh/RVRlpClWlrGZgBoI7qXD6Lphft9ZtO331G91TC8L3OkFw+kdpxjsQoH5sVqWuRU7PybcR1SK0os+LmoD3c4clFgSY/x1/g2Gm8FJrLNd5koRvRgAlnTScwPuvkQxSpAIq1/1ztLVVK+UCCJWThV9wukRADziXl/XSgQXPD3ToU+dIucWtd7Y2amm3ejRZzU43ZTugkUdLxm1cqyblvVvPfdNhKQgAPp/YJI+FO2JO0SWUfQa+nh2g03FIhBL6zKj9fehTYrhizO8=
addons:
  coverity_scan:
    project:
      name: MateMonkey/matemonkey4j
      description: Build submitted via Travis CI
    notification_email: iulius@sniggle.me
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
before_install:
- pip install --user codecov
after_success:
- codecov
