language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "FUo3RY47eEM2HTKFhreaRDa0OEqW+0c5bS8/q+mJ0+Me+qehrzVuughCZnxgHSerht06HcUIJ8GFhIQBUuFZi3/4P725vapCMUGPlSzkpji/ZTtb/EUo3YduzZcI4HPV8jwQnFQSuHfLW71bk8R2L0moPWR4ohJrGa3u7/bUyMfow1z1JuzGI8ghzuFunfpZvZIFTc/o54Sm8b3W2J+5vcpBBQ7axpwHitNJ2cAULbEWVwciNKU196zU/eY6x8ZBPTICtProJGge8AmgMkJyuUPjXYuOpRxloV8UZxW3WuMdnWjVvROqOxJI5sq1+THVEObWKuDscdrSKhZjvH3Ntn/MJZDff2GLOC3eqh0R3UE/Hi/p/x+x6zUjMMjs+dINLLui2vcuh6rpYI9wiWuYSCSeMC4b/Nhdi6ROM6s3a08HcKdr0Vqke2ZgTJSHMq/LLG5qFkIJsbm1RH4Qj6P85yZU++kL9lZ6Lo06/YNNCGQjthOzqxiE3Fov5/o50lgTKjAj21JA7ODTWkoD2obAQzi49cVnnbyYzlZ3Jjf6a6y+qsH/aPOZFkwTz2KCzq6yPmxvFNj7ZBPtTKYo/vFtrTQwu3yaW/jiHKy7nJ29hne5w+r3j3R3stylaaDm1hLSRdiaEtfC/HsAEKvXLOmZax7bErH8DT50/7RYli4Pi2A="
addons:
  coverity_scan:
    project:
      name: MateMonkey/matemonkey4j
      description: Build submitted via Travis CI
    notification_email: iulius@sniggle.me
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
before_install:
- pip install --user codecov
after_success:
- codecov
